replicaCount: 1

image:
  repository: themoah/go-web-tools
  tag: 0.2.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: 
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 200m
     memory: 256Mi

